// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgQof_oew0EJOU5-8a_IbJKa8cdtA5hWw',
    appId: '1:465365318309:web:71efee5100311e62ec2b4c',
    messagingSenderId: '465365318309',
    projectId: 'apktkfa',
    authDomain: 'apktkfa.firebaseapp.com',
    storageBucket: 'apktkfa.firebasestorage.app',
    measurementId: 'G-2MSKHJM2YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRtoEj9u5x2iQ_6jcSW6oBowKDObxjDOU',
    appId: '1:465365318309:android:56d397662527d4a4ec2b4c',
    messagingSenderId: '465365318309',
    projectId: 'apktkfa',
    storageBucket: 'apktkfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMJFEge2ha_gMuVCUPLvI0uTFiSvg1Z7Q',
    appId: '1:465365318309:ios:933655e5d0b76c1aec2b4c',
    messagingSenderId: '465365318309',
    projectId: 'apktkfa',
    storageBucket: 'apktkfa.firebasestorage.app',
    iosBundleId: 'com.example.choraleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMJFEge2ha_gMuVCUPLvI0uTFiSvg1Z7Q',
    appId: '1:465365318309:ios:933655e5d0b76c1aec2b4c',
    messagingSenderId: '465365318309',
    projectId: 'apktkfa',
    storageBucket: 'apktkfa.firebasestorage.app',
    iosBundleId: 'com.example.choraleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgQof_oew0EJOU5-8a_IbJKa8cdtA5hWw',
    appId: '1:465365318309:web:0c4582e9567f11feec2b4c',
    messagingSenderId: '465365318309',
    projectId: 'apktkfa',
    authDomain: 'apktkfa.firebaseapp.com',
    storageBucket: 'apktkfa.firebasestorage.app',
    measurementId: 'G-H7SVXWQLH2',
  );
}
